kr_optimization_tech_card_name = "space-science-pack"
require("__Krastorio2__/prototypes/compatibility/space-exploration-pre")

-- Library - to be deprecated
krastorio = {}
require("__Krastorio2__/lib/private/data-stages/utils/krastorio_utils")
require("__Krastorio2__/lib/private/data-stages/entities")
require("__Krastorio2__/lib/private/data-stages/equipments")
require("__Krastorio2__/lib/private/data-stages/general")
require("__Krastorio2__/lib/private/data-stages/icons")
require("__Krastorio2__/lib/private/data-stages/items")
require("__Krastorio2__/lib/private/data-stages/modules")
require("__Krastorio2__/lib/private/data-stages/recipes")
require("__Krastorio2__/lib/private/data-stages/technologies")

require("__Krastorio2__/prototypes/achievements/achievements-initialization")
require("__Krastorio2__/prototypes/categories/categories-initialization")
require("__Krastorio2__/prototypes/damages/damages-initialization")
require("__Krastorio2__/prototypes/entities/entities-initialization")
require("__Krastorio2__/prototypes/equipments/equipments-initialization")
require("__Krastorio2__/prototypes/fluids/fluids-initialization")
require("__Krastorio2__/prototypes/gui/gui-initialization")
require("__Krastorio2__/prototypes/gui/tips-and-tricks-initialization")
require("__Krastorio2__/prototypes/items/items-initialization")
require("__Krastorio2__/prototypes/particles/particles-initialization")
require("__Krastorio2__/prototypes/recipes/recipes-initialization")
require("__Krastorio2__/prototypes/resources/resources-initialization")
require("__Krastorio2__/prototypes/sounds/sounds")
require("__Krastorio2__/prototypes/technologies/technologies-initialization")
require("__Krastorio2__/prototypes/tiles/tiles-initialization")
require("__Krastorio2__/prototypes/others/virtual-signals-initialization")
require("__Krastorio2__/prototypes/others/key-bind-initialization")
require("__Krastorio2__/prototypes/others/shortcut")

require("__Krastorio2__/compatibility-scripts/data/aircraft")
require("__Krastorio2__/compatibility-scripts/data/early-electric-furnaces")
require("__Krastorio2__/compatibility-scripts/data/deadlock-beltboxes-loaders")
require("__Krastorio2__/compatibility-scripts/data/Squeak_Through")
