require("__Krastorio2__/compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-chaingunner")
require("__Krastorio2__/compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-flame-tank")
require("__Krastorio2__/compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-flame-tumbler")
require("__Krastorio2__/compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-hauler")
require("__Krastorio2__/compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-laser-tank")
require("__Krastorio2__/compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-miner")
require("__Krastorio2__/compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-warden")
